name: Groq Job Parser

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt to parse job information'
        required: true
        type: string

jobs:
  parse-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install Groq SDK
        run: pip install groq

      # Run the Python script
      - name: Run Groq job parser
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PROMPT: ${{ github.event.inputs.prompt }}
        run: python parse_job.py "$PROMPT"

      # Store the output
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: job-output
          path: job_output.json
